/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package genericbillingsoftware;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author rohit
 */
public class LogIn extends javax.swing.JFrame {

    private Color errorColor;
    public LogIn() {
        errorColor = new Color(255, 186, 186);
        initComponents();
        
        loginEmail.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public
            void insertUpdate(DocumentEvent e) {
                warn();
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void removeUpdate(DocumentEvent e) {
                warn();
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void changedUpdate(DocumentEvent e) {
                warn();
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
            public void warn()
                {
                    String regex = "^[a-zA-Z0-9]+[a-zA-Z0-9.]*[a-zA-Z0-9.]+@[a-zA-Z0-9]+.[a-zA-Z]+";
                    Pattern p = Pattern.compile(regex);
                    Matcher m = p.matcher(loginEmail.getText());
                    if(!loginEmail.getText().equals("") && !m.matches())
                        loginEmail.setBackground(errorColor);
                    else
                        loginEmail.setBackground(Color.WHITE);
                }
        });
        loginPassword.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public
            void insertUpdate(DocumentEvent e) {
                warn();
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void removeUpdate(DocumentEvent e) {
                warn();
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void changedUpdate(DocumentEvent e) {
                warn();
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
            public void warn()
                {
                    if(0<loginPassword.getPassword().length && loginPassword.getPassword().length<8)
                        loginPassword.setBackground(errorColor);
                    else
                        loginPassword.setBackground(Color.WHITE);
                }
        });
    }

/**
     * Creates new form LogIn
     */
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        loginCloseApp = new javax.swing.JButton();
        loginShowPassword = new javax.swing.JCheckBox();
        loginEmail = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        loginForgotPassword = new javax.swing.JLabel();
        loginCreateButton = new javax.swing.JButton();
        loginPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel1.setText("LOGIN");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = -11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(340, 66, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        loginCloseApp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loginCloseApp.setText("CLOSE");
        loginCloseApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginCloseAppMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 30, 0, 0);
        getContentPane().add(loginCloseApp, gridBagConstraints);

        loginShowPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginShowPassword.setText("Show Password");
        loginShowPassword.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                loginShowPasswordStateChanged(evt);
            }
        });
        loginShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginShowPasswordActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 0, 0, 615);
        getContentPane().add(loginShowPassword, gridBagConstraints);

        loginEmail.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        loginEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginEmailFocusLost(evt);
            }
        });
        loginEmail.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                loginEmailInputMethodTextChanged(evt);
            }
        });
        loginEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginEmailActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 334;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 26, 0, 0);
        getContentPane().add(loginEmail, gridBagConstraints);

        loginButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loginButton.setText("LOGIN");
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginButtonMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 36, 0, 0);
        getContentPane().add(loginButton, gridBagConstraints);

        loginForgotPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginForgotPassword.setText("Forgot Password?");
        loginForgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginForgotPasswordMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        getContentPane().add(loginForgotPassword, gridBagConstraints);

        loginCreateButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loginCreateButton.setText("CREATE NEW ACCOUNT");
        loginCreateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginCreateButtonMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 29;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 36, 329, 0);
        getContentPane().add(loginCreateButton, gridBagConstraints);

        loginPassword.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 334;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 26, 0, 0);
        getContentPane().add(loginPassword, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 703, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(44, 703, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginShowPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginShowPasswordActionPerformed

    private void loginEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginEmailActionPerformed

    private void loginEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginEmailFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginEmailFocusGained

    private void loginEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginEmailFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_loginEmailFocusLost

    private void loginEmailInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_loginEmailInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_loginEmailInputMethodTextChanged

    private void loginShowPasswordStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_loginShowPasswordStateChanged
        // TODO add your handling code here:
        if(loginShowPassword.isSelected())
            loginPassword.setEchoChar((char)0);
        else
            loginPassword.setEchoChar('*');
    }//GEN-LAST:event_loginShowPasswordStateChanged

    private void loginForgotPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginForgotPasswordMousePressed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Contact Administrator for password reset!");
    }//GEN-LAST:event_loginForgotPasswordMousePressed

    private void loginCloseAppMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginCloseAppMousePressed
        // TODO add your handling code here:
        JLabel message = new JLabel("Are you sure to exit?");
        message.setFont(new Font("Tahoma",0,18));
        int res = JOptionPane.showConfirmDialog(null, message, "Close", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(res==JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_loginCloseAppMousePressed

    private void loginButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMousePressed
        // TODO add your handling code here:
        if(loginEmail.getBackground()==errorColor || loginEmail.getText().toString().length()==0)
            JOptionPane.showMessageDialog(null, "Invalid Email");
        else if(loginPassword.getBackground()==errorColor || loginPassword.getText().length()==0)
            JOptionPane.showMessageDialog(null, "Password must of at least 8 characters");
        else
        {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            String loginAccountResult = SqlQueries.loginAccount(loginEmail.getText(), loginPassword.getText());
            this.setCursor(Cursor.getDefaultCursor());
            if(loginAccountResult.equals(Boolean.toString(true)))
            {
                String user_name = SqlQueries.getUserName(loginEmail.getText());
                String user_type = SqlQueries.getUserType(loginEmail.getText());
                if(Integer.parseInt(user_type)==1)
                {
                    StandardDashBoard db = new StandardDashBoard();
                    db.setLoggedInName(user_name);
                    db.setLoggedInEmail(loginEmail.getText());
                    db.setVisible(true);
                }
                else
                {
                    
                }
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(null, loginAccountResult);
            }
        }
        loginPassword.setText("");
    }//GEN-LAST:event_loginButtonMousePressed

    private void loginCreateButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginCreateButtonMousePressed
        // TODO add your handling code here:
        new CreateAccount().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginCreateButtonMousePressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton loginCloseApp;
    private javax.swing.JButton loginCreateButton;
    private javax.swing.JTextField loginEmail;
    private javax.swing.JLabel loginForgotPassword;
    private javax.swing.JPasswordField loginPassword;
    private javax.swing.JCheckBox loginShowPassword;
    // End of variables declaration//GEN-END:variables
}
