/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package genericbillingsoftware;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author rohit
 */
public
        class RemoveItem extends javax.swing.JPanel {

    /**
     * Creates new form RemoveItem
     */
    public void getItemsID()
    {
        Object[] items = SqlQueries.getItems(SqlQueries.INT_TYPE);
        jComboBox1.removeAllItems();
        jComboBox1.addItem(null);
        for(Object item:items)
            jComboBox1.addItem((String) item);
        jComboBox1.setSelectedItem(null);
    }
    public void getItemsName()
    {
        Object[] items = SqlQueries.getItems(SqlQueries.STRING_TYPE);
        jComboBox2.removeAllItems();
        jComboBox2.addItem(null);
        for(Object item:items)
            jComboBox2.addItem((String) item);
        jComboBox2.setSelectedItem(null);
    }
    public
            RemoveItem() {
        initComponents();
        getItemsID();
        getItemsName();
        itemResetMousePressed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        itemRemove = new javax.swing.JButton();
        itemReset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        itemClose = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        curName = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        curID = new javax.swing.JTextField();
        curCost = new javax.swing.JTextField();
        curActive13 = new javax.swing.JLabel();
        curActive = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("OR");

        itemRemove.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        itemRemove.setText("Remote Item");
        itemRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                itemRemoveMousePressed(evt);
            }
        });

        itemReset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        itemReset.setText("Reset");
        itemReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                itemResetMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Current ID:");

        itemClose.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        itemClose.setText("Close");
        itemClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                itemCloseMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Current Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Select      ID");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Current Cost:");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        curName.setEditable(false);
        curName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        curID.setEditable(false);
        curID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        curCost.setEditable(false);
        curCost.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        curActive13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        curActive13.setText("Current Active:");

        curActive.setEditable(false);
        curActive.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        curActive.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(itemClose))
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(itemRemove)
                                .addGap(78, 78, 78)
                                .addComponent(itemReset))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(curActive13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(curActive, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(curID, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(curCost, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(curName, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(itemClose)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(curID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(curName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(curCost, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(curActive13)
                    .addComponent(curActive, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemRemove)
                    .addComponent(itemReset))
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void itemRemoveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemRemoveMousePressed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem()==null || jComboBox2.getSelectedItem()==null)
        {
            JLabel message = new JLabel();
            message.setText("Please select an Item to remove!");
            message.setFont(new Font("Tahoma", 0, 18));
            JOptionPane.showMessageDialog(null, message);
        }
        else
        {
            JLabel message = new JLabel();
            message.setText("Are you sure to remove the item?");
            message.setFont(new Font("Tahoma",0,18));
            int confirmRemove = JOptionPane.showConfirmDialog(null, message, "Remove item?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(confirmRemove==JOptionPane.YES_OPTION)
            {
                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                String removeResult = SqlQueries.delItem(Integer.parseInt(curID.getText()));
                this.setCursor(Cursor.getDefaultCursor());
                if(removeResult.equals("true"))
                {
                    message.setText("Item removed successfully!");
                    itemResetMousePressed(null);
                    getItemsID();
                    getItemsName();
                    JOptionPane.showMessageDialog(null, message);
                }
                else
                {
                    message.setText(removeResult);
                    JOptionPane.showMessageDialog(null, message);
                }
            }
        }
    }//GEN-LAST:event_itemRemoveMousePressed

    private void itemResetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemResetMousePressed
        // TODO add your handling code here:
        jComboBox1.setSelectedItem(null);
        jComboBox2.setSelectedItem(null);
        curID.setBackground(new Color(240,240,240));
        curName.setBackground(new Color(240,240,240));
        curCost.setBackground(new Color(240,240,240));
        curActive.setBackground(new Color(240,240,240));
        curID.setText("");
        curCost.setText("");
        curName.setText("");
        curActive.setText("");
    }//GEN-LAST:event_itemResetMousePressed

    private void itemCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemCloseMousePressed
        // TODO add your handling code here:
        JDialog dialog = (JDialog) this.getRootPane().getParent();
        dialog.getParent().setEnabled(true);
        dialog.dispose();
    }//GEN-LAST:event_itemCloseMousePressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem()==null)
            itemResetMousePressed(null);
        else
        {
            ItemObject item = SqlQueries.getItemFromID((String) jComboBox1.getSelectedItem());
            jComboBox2.setSelectedItem(item.getName());
            curCost.setText(item.getCost());
            curID.setText(item.getID());
            curName.setText(item.getName());
            if(item.isActive().equals("true"))
                curActive.setText("YES");
            else
                curActive.setText("NO");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        if(jComboBox2.getSelectedItem()==null)
        itemResetMousePressed(null);
        else
        {
            ItemObject item = SqlQueries.getItemFromName((String) jComboBox2.getSelectedItem());
            jComboBox1.setSelectedItem(item.getID());
            curCost.setText(item.getCost());
            curID.setText(item.getID());
            curName.setText(item.getName());
            if(item.isActive().equals("true"))
                curActive.setText("YES");
            else
                curActive.setText("NO");
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField curActive;
    private javax.swing.JLabel curActive13;
    private javax.swing.JTextField curCost;
    private javax.swing.JTextField curID;
    private javax.swing.JTextField curName;
    private javax.swing.JButton itemClose;
    private javax.swing.JButton itemRemove;
    private javax.swing.JButton itemReset;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
