/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package genericbillingsoftware;

import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rohit
 */
public
        class StandardDashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    private String logged_in_name,logged_in_email;
    public String getLoggedInName()
    {
        return logged_in_name;
    }
    public String getLoggedInEmail()
    {
        return logged_in_email;
    }
    public void setLoggedInName(String name)
    {
        logged_in_name = name;
        viewName.setText(logged_in_name);
    }
    public void setLoggedInEmail(String email)
    {
        logged_in_email = email;
        viewEmail.setText(logged_in_email);
    }
    public
            StandardDashBoard() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardRemoveItems = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        dashboardAddItem = new javax.swing.JButton();
        dashboardEditItem = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        dashboardViewItems = new javax.swing.JButton();
        dashboardLogOut = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        updateEmail = new javax.swing.JButton();
        updateName = new javax.swing.JButton();
        deleteAccount = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        dashboardClose = new javax.swing.JButton();
        changePasswordButton = new javax.swing.JButton();
        viewName = new javax.swing.JLabel();
        viewEmail = new javax.swing.JLabel();
        viewName2 = new javax.swing.JLabel();
        viewName3 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1940, 1100));
        setUndecorated(true);
        setResizable(false);

        dashboardRemoveItems.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dashboardRemoveItems.setText("Remove Item");
        dashboardRemoveItems.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dashboardRemoveItems.setDoubleBuffered(true);
        dashboardRemoveItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dashboardRemoveItemsMousePressed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Add Bill");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.setDoubleBuffered(true);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        dashboardAddItem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dashboardAddItem.setText("Add Item");
        dashboardAddItem.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dashboardAddItem.setDoubleBuffered(true);
        dashboardAddItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dashboardAddItemMousePressed(evt);
            }
        });

        dashboardEditItem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dashboardEditItem.setText("Edit Item");
        dashboardEditItem.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dashboardEditItem.setDoubleBuffered(true);
        dashboardEditItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dashboardEditItemMousePressed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("View Bills");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.setDoubleBuffered(true);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton5MousePressed(evt);
            }
        });

        dashboardViewItems.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dashboardViewItems.setText("View Items");
        dashboardViewItems.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dashboardViewItems.setDoubleBuffered(true);
        dashboardViewItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dashboardViewItemsMousePressed(evt);
            }
        });

        dashboardLogOut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dashboardLogOut.setText("Log Out");
        dashboardLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dashboardLogOut.setDoubleBuffered(true);
        dashboardLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dashboardLogOutMousePressed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8.setText("Add Customer");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton8.setDoubleBuffered(true);
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton8MousePressed(evt);
            }
        });

        updateEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updateEmail.setText("Update Email");
        updateEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        updateEmail.setDoubleBuffered(true);
        updateEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                updateEmailMousePressed(evt);
            }
        });

        updateName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updateName.setText("Update Name");
        updateName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        updateName.setDoubleBuffered(true);
        updateName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                updateNameMousePressed(evt);
            }
        });

        deleteAccount.setBackground(new java.awt.Color(255, 153, 153));
        deleteAccount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deleteAccount.setText("Delete Account");
        deleteAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        deleteAccount.setDoubleBuffered(true);
        deleteAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deleteAccountMousePressed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton14.setText("Edit Customer");
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton14.setDoubleBuffered(true);
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton14MousePressed(evt);
            }
        });

        dashboardClose.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dashboardClose.setText("Close");
        dashboardClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dashboardClose.setDoubleBuffered(true);
        dashboardClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dashboardCloseMousePressed(evt);
            }
        });

        changePasswordButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        changePasswordButton.setText("Change Password");
        changePasswordButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        changePasswordButton.setDoubleBuffered(true);
        changePasswordButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                changePasswordButtonMousePressed(evt);
            }
        });

        viewName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        viewEmail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        viewName2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        viewName2.setText("Email:");

        viewName3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        viewName3.setText("Name:");

        jButton15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton15.setText("View Customers");
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton15.setDoubleBuffered(true);
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton15MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1850, 1850, 1850)
                .addComponent(dashboardClose))
            .addGroup(layout.createSequentialGroup()
                .addGap(1830, 1830, 1830)
                .addComponent(dashboardLogOut))
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewName2)
                    .addComponent(viewName3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dashboardAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(dashboardViewItems)
                        .addGap(17, 17, 17)
                        .addComponent(dashboardRemoveItems)
                        .addGap(19, 19, 19)
                        .addComponent(dashboardEditItem, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jButton8)
                        .addGap(18, 18, 18)
                        .addComponent(jButton15)
                        .addGap(18, 18, 18)
                        .addComponent(jButton14))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(viewName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateName)
                .addGap(18, 18, 18)
                .addComponent(updateEmail)
                .addGap(18, 18, 18)
                .addComponent(changePasswordButton)
                .addGap(18, 18, 18)
                .addComponent(deleteAccount)
                .addGap(632, 632, 632))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dashboardClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dashboardLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dashboardAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dashboardViewItems, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dashboardRemoveItems, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dashboardEditItem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(313, 313, 313)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewName3))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewName2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 384, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changePasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardLogOutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardLogOutMousePressed
        // TODO add your handling code here:
        JLabel message = new JLabel("Are you sure to Log Out?");
        message.setFont(new Font("Tahoma",0,18));
        int sureLogOut = JOptionPane.showConfirmDialog(null, message, "LogOut?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(sureLogOut==JOptionPane.YES_OPTION)
        {
            new LogIn().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_dashboardLogOutMousePressed

    private void dashboardCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardCloseMousePressed
        // TODO add your handling code here:
        JLabel message = new JLabel("Are you sure you want to exit?");
        message.setFont(new Font("Tahoma", 0, 18));
        int result = JOptionPane.showConfirmDialog(null, message, "Exit?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(result==JOptionPane.YES_OPTION)
            this.dispose();
    }//GEN-LAST:event_dashboardCloseMousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
        this.setEnabled(false);
        AddBill addBillPanel = new AddBill();
        addBillPanel.setStaff(logged_in_name, logged_in_email);
        JDialog dialog = new JDialog(this);
        dialog.getContentPane().add(addBillPanel);
        dialog.pack();
        dialog.setVisible(true);
        dialog.setLocationRelativeTo(this);
        dialog.setResizable(false);
        dialog.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        dialog.addWindowListener(new WindowListener(){
            @Override
            public
            void windowOpened(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowClosing(WindowEvent e) {
                JLabel message = new JLabel("Are you sure?");
                message.setFont(new Font("Tahoma",0,18));
                int confirm = JOptionPane.showConfirmDialog(null, message, "Close?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if(confirm==JOptionPane.YES_OPTION)
                {
                    dialog.getParent().setEnabled(true);
                    dialog.dispose();
                }
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowClosed(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowIconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowDeiconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowActivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowDeactivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }//GEN-LAST:event_jButton2MousePressed

    private void dashboardAddItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardAddItemMousePressed
        // TODO add your handling code here:
        this.setEnabled(false);
        AddItem addItemPanel = new AddItem();
        JDialog dialog = new JDialog(this);
        dialog.getContentPane().add(addItemPanel);
        dialog.pack();
        dialog.setVisible(true);
        dialog.setLocationRelativeTo(this);
        dialog.setResizable(false);
        dialog.addWindowListener(new WindowListener(){
            @Override
            public
            void windowOpened(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowClosing(WindowEvent e) {
                dialog.getParent().setEnabled(true);
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowClosed(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowIconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowDeiconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowActivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowDeactivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }//GEN-LAST:event_dashboardAddItemMousePressed

    private void dashboardEditItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardEditItemMousePressed
        // TODO add your handling code here:
        this.setEnabled(false);
        EditItem editItemPanel = new EditItem();
        JDialog dialog = new JDialog(this);
        dialog.getContentPane().add(editItemPanel);
        dialog.pack();
        dialog.setVisible(true);
        dialog.setLocationRelativeTo(this);
        dialog.setResizable(false);
        dialog.addWindowListener(new WindowListener(){
            @Override
            public
            void windowOpened(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowClosing(WindowEvent e) {
                dialog.getParent().setEnabled(true);
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowClosed(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowIconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowDeiconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowActivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowDeactivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }//GEN-LAST:event_dashboardEditItemMousePressed

    private void dashboardViewItemsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardViewItemsMousePressed
        // TODO add your handling code here:
        JDialog dialog = new JDialog(this);
        this.setEnabled(false);
        JPanel viewPanel = new ViewItems();
        dialog.getContentPane().add(viewPanel);
        dialog.pack();
        dialog.setVisible(true);
        dialog.setLocationRelativeTo(this);
        dialog.setResizable(false);
        dialog.addWindowListener(new WindowListener(){
            @Override
            public
            void windowOpened(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowClosing(WindowEvent e) {
                dialog.getParent().setEnabled(true);
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowClosed(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowIconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowDeiconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowActivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowDeactivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }//GEN-LAST:event_dashboardViewItemsMousePressed

    private void dashboardRemoveItemsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardRemoveItemsMousePressed
        // TODO add your handling code here:
        JDialog dialog = new JDialog(this);
        this.setEnabled(false);
        JPanel removePanel = new RemoveItem();
        dialog.getContentPane().add(removePanel);
        dialog.pack();
        dialog.setVisible(true);
        dialog.setLocationRelativeTo(this);
        dialog.setResizable(false);
        dialog.addWindowListener(new WindowListener(){
            @Override
            public
            void windowOpened(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowClosing(WindowEvent e) {
                dialog.getParent().setEnabled(true);
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowClosed(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowIconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowDeiconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowActivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowDeactivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }//GEN-LAST:event_dashboardRemoveItemsMousePressed

    private void changePasswordButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswordButtonMousePressed
        // TODO add your handling code here:
        JDialog dialog = new JDialog(this);
        this.setEnabled(false);
        JPanel changePasswordPanel = new ChangePassword();
        dialog.getContentPane().add(changePasswordPanel);
        dialog.pack();
        dialog.setVisible(true);
        dialog.setLocationRelativeTo(this);
        dialog.setResizable(false);
        dialog.addWindowListener(new WindowListener(){
            @Override
            public
            void windowOpened(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowClosing(WindowEvent e) {
                dialog.getParent().setEnabled(true);
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowClosed(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowIconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowDeiconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowActivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowDeactivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }//GEN-LAST:event_changePasswordButtonMousePressed

    private void deleteAccountMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteAccountMousePressed
        // TODO add your handling code here:
        JLabel message = new JLabel("Are you sure you want to delete your account?");
        message.setFont(new Font("Tahoma",0,18));
        int confirm_result = JOptionPane.showConfirmDialog(null, message, "Delete Account?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(confirm_result==JOptionPane.YES_OPTION)
        {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            String deleted = SqlQueries.delAccount(logged_in_email);
            this.setCursor(Cursor.getDefaultCursor());
            if(deleted.equals("true"))
            {
                message.setText("Deleted Account successfully! Click OK to move to LogIn Page.");
                JOptionPane.showMessageDialog(null, message);
                new LogIn().setVisible(true);
                this.dispose();
            }
            else
            {
                message.setText("Account not deleted! Error: " + deleted);
                JOptionPane.showMessageDialog(null, message);
            }
        }
    }//GEN-LAST:event_deleteAccountMousePressed

    private void updateNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateNameMousePressed
        // TODO add your handling code here:
        JDialog dialog = new JDialog(this);
        this.setEnabled(false);
        JPanel updateNamePanel = new UpdateName();
        dialog.getContentPane().add(updateNamePanel);
        dialog.pack();
        dialog.setVisible(true);
        dialog.setLocationRelativeTo(this);
        dialog.setResizable(false);
        dialog.addWindowListener(new WindowListener(){
            @Override
            public
            void windowOpened(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowClosing(WindowEvent e) {
                dialog.getParent().setEnabled(true);
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowClosed(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowIconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowDeiconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowActivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowDeactivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }//GEN-LAST:event_updateNameMousePressed

    private void updateEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateEmailMousePressed
        // TODO add your handling code here:
        JDialog dialog = new JDialog(this);
        this.setEnabled(false);
        JPanel updateEmailPanel = new UpdateEmail();
        dialog.getContentPane().add(updateEmailPanel);
        dialog.pack();
        dialog.setVisible(true);
        dialog.setLocationRelativeTo(this);
        dialog.setResizable(false);
        dialog.addWindowListener(new WindowListener(){
            @Override
            public
            void windowOpened(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowClosing(WindowEvent e) {
                dialog.getParent().setEnabled(true);
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowClosed(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowIconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowDeiconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowActivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowDeactivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }//GEN-LAST:event_updateEmailMousePressed

    private void jButton8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MousePressed
        // TODO add your handling code here:
        JDialog dialog = new JDialog(this);
        this.setEnabled(false);
        JPanel addCustomerPanel = new AddCustomer();
        dialog.getContentPane().add(addCustomerPanel);
        dialog.pack();
        dialog.setVisible(true);
        dialog.setLocationRelativeTo(this);
        dialog.setResizable(false);
        dialog.addWindowListener(new WindowListener(){
            @Override
            public
            void windowOpened(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowClosing(WindowEvent e) {
                dialog.getParent().setEnabled(true);
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowClosed(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowIconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowDeiconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowActivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowDeactivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }//GEN-LAST:event_jButton8MousePressed

    private void jButton14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MousePressed
        // TODO add your handling code here:
        JDialog dialog = new JDialog(this);
        this.setEnabled(false);
        JPanel editCustomerPanel = new EditCustomer();
        dialog.getContentPane().add(editCustomerPanel);
        dialog.pack();
        dialog.setVisible(true);
        dialog.setLocationRelativeTo(this);
        dialog.setResizable(false);
        dialog.addWindowListener(new WindowListener(){
            @Override
            public
            void windowOpened(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowClosing(WindowEvent e) {
                dialog.getParent().setEnabled(true);
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowClosed(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowIconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowDeiconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowActivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowDeactivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }//GEN-LAST:event_jButton14MousePressed

    private void jButton15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MousePressed
        // TODO add your handling code here:
        JDialog dialog = new JDialog(this);
        this.setEnabled(false);
        JPanel viewCustomersPanel = new ViewCustomers();
        dialog.getContentPane().add(viewCustomersPanel);
        dialog.pack();
        dialog.setVisible(true);
        dialog.setLocationRelativeTo(this);
        dialog.setResizable(false);
        dialog.addWindowListener(new WindowListener(){
            @Override
            public
            void windowOpened(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowClosing(WindowEvent e) {
                dialog.getParent().setEnabled(true);
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowClosed(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowIconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowDeiconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowActivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowDeactivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }//GEN-LAST:event_jButton15MousePressed

    private void jButton5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MousePressed
        // TODO add your handling code here:
        JDialog dialog = new JDialog(this);
        this.setEnabled(false);
        JPanel viewBillsPanel = new ViewBills();
        dialog.getContentPane().add(viewBillsPanel);
        dialog.pack();
        dialog.setVisible(true);
        dialog.setLocationRelativeTo(this);
        dialog.setResizable(false);
        dialog.addWindowListener(new WindowListener(){
            @Override
            public
            void windowOpened(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowClosing(WindowEvent e) {
                dialog.getParent().setEnabled(true);
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowClosed(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowIconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowDeiconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowActivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public
            void windowDeactivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }//GEN-LAST:event_jButton5MousePressed
    /**
     * @param args the command line arguments
     */
    public static
            void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StandardDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StandardDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StandardDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StandardDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public
                    void run() {
                new StandardDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changePasswordButton;
    private javax.swing.JButton dashboardAddItem;
    private javax.swing.JButton dashboardClose;
    private javax.swing.JButton dashboardEditItem;
    private javax.swing.JButton dashboardLogOut;
    private javax.swing.JButton dashboardRemoveItems;
    private javax.swing.JButton dashboardViewItems;
    private javax.swing.JButton deleteAccount;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton updateEmail;
    private javax.swing.JButton updateName;
    private javax.swing.JLabel viewEmail;
    private javax.swing.JLabel viewName;
    private javax.swing.JLabel viewName2;
    private javax.swing.JLabel viewName3;
    // End of variables declaration//GEN-END:variables
}
